=pod

=head1 NAME

rtrim - Entfernt Whitespace am Ende einer Zeile

=head1 SYNOPSIS

B<rtrim>

=head1 DESCRIPTION

Liest Zeilenweise von der Standardeingabe und entfernt Leerraum (Whitespace)
am Ende einer Zeile. Schreibt auf die Standardausgabe.

Eine Alternative kann dieses sed-Skript sein:

	#!/usr/bin/env sed -f
	# Entfernt Leerraum (Whitespace) am Ende/rechts
	s/\s*$//;

=head1 SEE ALSO

L<Text::Trim(3pm)>, L<trim(1)>

=cut

